[tool.poetry]
name = "python-test-repository"
version = "0.1.0"
description = ""
authors = ["clickharder <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
poetry = "^1.1.13"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
